CREATE TABLE IF NOT EXISTS categories (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    color VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE;

MERGE INTO categories (id, name, color) KEY(id) VALUES
    (1, '仕事', '#0d6efd'),
    (2, '学習', '#fd7e14'),
    (3, '個人', '#198754');

CREATE TABLE IF NOT EXISTS todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(50) NOT NULL DEFAULT '',
    user_id BIGINT NOT NULL DEFAULT 1,
    priority VARCHAR(10) NOT NULL DEFAULT 'MEDIUM',
    category_id BIGINT NOT NULL DEFAULT 1,
    deadline DATE,
    display_order INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'TODO',
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_todos_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_todos_user FOREIGN KEY (user_id) REFERENCES users (id)
);

ALTER TABLE todos ADD COLUMN IF NOT EXISTS priority VARCHAR(10) NOT NULL DEFAULT 'MEDIUM';
ALTER TABLE todos ADD COLUMN IF NOT EXISTS category_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS deadline DATE;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS display_order INT NOT NULL DEFAULT 0;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'TODO';
ALTER TABLE todos ADD COLUMN IF NOT EXISTS author VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE todos ADD COLUMN IF NOT EXISTS user_id BIGINT NOT NULL DEFAULT 1;
UPDATE todos SET category_id = 1 WHERE category_id IS NULL;
UPDATE todos SET user_id = 1 WHERE user_id IS NULL;
UPDATE todos SET display_order = id WHERE display_order IS NULL OR display_order = 0;
UPDATE todos SET status = 'DONE' WHERE completed = TRUE;
UPDATE todos SET status = 'TODO' WHERE completed = FALSE AND (status IS NULL OR status = '');

CREATE TABLE IF NOT EXISTS todo_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_id BIGINT NOT NULL,
    action VARCHAR(30) NOT NULL,
    detail VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(30) NOT NULL,
    entity_type VARCHAR(50),
    entity_id BIGINT,
    user_id BIGINT,
    old_value CLOB,
    new_value CLOB,
    ip_address VARCHAR(64),
    status VARCHAR(20) NOT NULL,
    message VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS entity_type VARCHAR(50);
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS entity_id BIGINT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS old_value CLOB;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS new_value CLOB;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS ip_address VARCHAR(64);

CREATE TABLE IF NOT EXISTS todo_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_id BIGINT NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    stored_file_name VARCHAR(255) NOT NULL UNIQUE,
    content_type VARCHAR(100),
    file_size BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_todo_attachments_todo FOREIGN KEY (todo_id) REFERENCES todos (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS weekly_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_start DATE NOT NULL,
    week_end DATE NOT NULL,
    created_count INT NOT NULL,
    completed_count INT NOT NULL,
    completion_rate INT NOT NULL,
    category_breakdown CLOB,
    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_weekly_reports_week UNIQUE (week_start, week_end)
);

CREATE TABLE IF NOT EXISTS label_colors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    label_key VARCHAR(50) NOT NULL,
    color VARCHAR(20) NOT NULL,
    CONSTRAINT fk_label_colors_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_label_colors_user_key UNIQUE (user_id, label_key)
);
